Repository catholichak2024/cathak_Backend, pull requests merged in 2024-10, with the labels that each got.

#4 [FEAT] 프로젝트 초기 세팅
  .gitignore
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/db.config.js
  src/errors.js
  src/index.js
Labels: :sparkles: FEATURE, :gear: CHORE

#5 [feat] test
  src/test.js
Labels: :sparkles: FEATURE

#6 [FEAT] CI/CD 파이프라인 구축
  .github/workflows/deploy-dev.yml
Labels: :sparkles: FEATURE, :gear: CHORE

#8 [FEAT] 헬스케어 테스트
  src/domains/health/health.controller.js
  src/index.js
  src/routes/health.js
  src/test.js
Labels: :sparkles: FEATURE, :gear: CHORE

#10 [FEAT] 폴더 구조 생성
  src/domains/login/login.controller.js
  src/domains/login/login.dto.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/routes/login.js
Labels: :sparkles: FEATURE

#12 [FEAT] 회원가입
  package.json
  pnpm-lock.yaml
  src/db.config.js
  src/domains/login/login.controller.js
  src/domains/login/login.dto.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/domains/login/login.sql.js
  src/errors.js
  src/index.js
  src/response.js
  src/response.status.js
  src/routes/login.js
  src/swagger/login.swagger.yaml
  src/swagger/swagger.config.js
Labels: :sparkles: FEATURE

#19 [FEAT] 로그인
  package.json
  pnpm-lock.yaml
  src/domains/login/login.controller.js
  src/domains/login/login.dto.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/middlewares/token.auth.js
  src/response.status.js
  src/routes/health.js
  src/routes/login.js
Labels: :sparkles: FEATURE

#21 [FEAT] 아이디 찾기
  src/domains/login/login.controller.js
  src/domains/login/login.dto.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/response.status.js
  src/routes/login.js
Labels: :sparkles: FEATURE

#23 [FEAT] 비밀번호 찾기
  src/domains/login/login.controller.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/routes/login.js
Labels: :sparkles: FEATURE

#25 [FEAT] 성적관리 불러오기
  src/domains/grade/grade.controller.js
  src/domains/grade/grade.dto.js
  src/domains/grade/grade.repository.js
  src/domains/grade/grade.service.js
  src/domains/grade/grade.sql.js
  src/index.js
  src/routes/grade.js
Labels: :sparkles: FEATURE

#28 [FEAT] 성적관리 수정하기
  src/domains/grade/grade.controller.js
  src/domains/grade/grade.repository.js
  src/domains/grade/grade.service.js
  src/domains/grade/grade.sql.js
  src/routes/grade.js
Labels: :sparkles: FEATURE

#30 [FEAT] 아이디 중복확인
  src/domains/login/login.controller.js
  src/domains/login/login.dto.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/routes/login.js
Labels: :sparkles: FEATURE

#32 [FEAT] 전공 검색
  src/domains/login/login.controller.js
  src/domains/login/login.dto.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/domains/login/login.sql.js
  src/routes/login.js
Labels: :sparkles: FEATURE

#36 [FEAT] 마이페이지
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.dto.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
  src/index.js
  src/routes/login.js
  src/routes/mypage.js
Labels: :sparkles: FEATURE

#40 [FEAT] 비밀번호 변경
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
  src/routes/mypage.js
Labels: :sparkles: FEATURE

#44 [FEAT] 회원가입 스웨거
  src/swagger/login.swagger.yaml
Labels: :memo: DOCS, :sparkles: FEATURE

#46 [FEAT] 스웨거 배포 서버 추가
  src/swagger/swagger.config.js
Labels: :sparkles: FEATURE

#48 [FEAT] 기초교양 상세화면
  src/domains/spec/mypage.service.js
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/index.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#50 [FEAT] 전공 전체 검색
  src/domains/login/login.controller.js
  src/domains/login/login.repository.js
  src/domains/login/login.service.js
  src/routes/login.js
Labels: :sparkles: FEATURE

#52 [FEAT] 기초교양 상세화면 필수요건
  src/domains/spec/mypage.service.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.sql.js
Labels: :sparkles: FEATURE

#55 [FEAT] 본영역 전공기초 상세화면
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#59 [FEAT] 타계열 전공기초 상세화면
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#18 [FEAT] 교양 화면
  src/domains/cultural/cultural.controller.js
  src/domains/cultural/cultural.service.js
  src/index.js
  src/routes/cultural.js
Labels: :sparkles: FEATURE

#27 [FEAT] 전공기초 화면
  src/domains/majorfoundation/majorfoundation.controller.js
  src/domains/majorfoundation/majorfoundation.service.js
  src/index.js
  src/routes/majorfoundation.js
Labels: :sparkles: FEATURE

#33 [FEAT] 전공 화면
  src/domains/major/major.controller.js
  src/domains/major/major.service.js
  src/index.js
  src/routes/major.js
  src/routes/majorfoundation.js
Labels: :sparkles: FEATURE

#63 [FEAT] 제1전공 상세화면
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#67 [FEAT] 부전공 상세화면
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#69 [FEAT] 타전공 상세화면
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#71 [FEAT] 상세화면 전공타입
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#73 [FEAT] 마이페이지 전공 검색
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.dto.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
  src/routes/mypage.js
Labels: :sparkles: FEATURE

#75 [FEAT] CORS 설정
  src/index.js
Labels: :sparkles: FEATURE

#77 [FEAT] CORS 추가 설정
  src/index.js
Labels: :sparkles: FEATURE, :gear: CHORE

#79 [FEAT] 마이페이지 전공 상세 검색
  src/domains/login/login.dto.js
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.dto.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
  src/routes/mypage.js
Labels: :sparkles: FEATURE

#57 [FEAT] 중핵 교양 상세화면
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#60 [FEAT] 자유교양 상세화면
  src/domains/spec/spec.controller.js
  src/domains/spec/spec.dto.js
  src/domains/spec/spec.repository.js
  src/domains/spec/spec.service.js
  src/domains/spec/spec.sql.js
  src/routes/spec.js
Labels: :sparkles: FEATURE

#42 [FEAT] 홈화면
  src/domains/home/home.controller.js
  src/domains/home/home.service.js
  src/index.js
  src/routes/home.js
Labels: :sparkles: FEATURE

#81 [FIX] 마이페이지 전공 검색
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.dto.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
  src/routes/mypage.js
Labels: :bug: FIX

#83 [FEAT] 수업 검색
  src/domains/mypage/mypage.controller.js
  src/domains/search/search.controller.js
  src/domains/search/search.dto.js
  src/domains/search/search.repository.js
  src/domains/search/search.service.js
  src/domains/search/search.sql.js
  src/index.js
  src/routes/cultural.js
  src/routes/major.js
  src/routes/majorfoundation.js
  src/routes/search.js
Labels: :sparkles: FEATURE

#85 [FEAT] 수업 검색 id 반환
  src/domains/search/search.controller.js
  src/domains/search/search.repository.js
  src/domains/search/search.service.js
  src/domains/search/search.sql.js
Labels: :sparkles: FEATURE

#87 [FIX] 검색화면 id 삭제
  src/domains/search/search.sql.js
Labels: :bug: FIX

#91 [FIX] 마이페이지 토큰 임시 삭제
  src/domains/mypage/mypage.controller.js
  src/routes/mypage.js
Labels: :bug: FIX

#95 [FIX] 토큰 req body에 반환
  src/domains/login/login.controller.js
Labels: :bug: FIX

#97 [FIX] 홈화면
  src/domains/home/home.controller.js
  src/domains/home/home.service.js
Labels: :bug: FIX, :sparkles: FEATURE

#101 [FIX] 수업검색 res 수정
  src/domains/search/search.dto.js
  src/domains/search/search.sql.js
Labels: :bug: FIX

#100 [FIX]홈화면 p/np 기능 추가
  src/domains/home/home.service.js
Labels: :bug: FIX, :sparkles: FEATURE

#105 [FIX] 마이페이지 전공 검색 수정
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.dto.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
  src/domains/search/search.repository.js
Labels: :bug: FIX

#106 [FEAT] 회원탈퇴
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.dto.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
  src/routes/mypage.js
Labels: :sparkles: FEATURE

#108 [FIX] 홈화면 교양 이수 학점
  src/domains/home/home.service.js
Labels: :bug: FIX

#110 [FEAT] 전공변경 시 검색어 입력
  src/domains/mypage/mypage.controller.js
  src/domains/mypage/mypage.repository.js
  src/domains/mypage/mypage.service.js
Labels: :sparkles: FEATURE
